# @package agent
_target_: agent.rl.Agent
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
num_expl_steps: 1000
hidden_dim: ${suite.hidden_dim}
stddev_schedule: 0.3
stddev_clip: 0.3
